name: Test

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

    workflow_dispatch:

jobs:
  gcc:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y g++ cmake libasio-dev socat qt6-base-dev qt6-serialport-dev

      - name: Configure CMake
        run: cmake -S . -B build -DPROTOCOMM_BUILD_TESTS=ON -DPROTOCOMM_BUILD_ASIO=ON -DPROTOCOMM_BUILD_QT=ON

      - name: Build
        run: cmake --build build

      - name: Run
        run: |
          echo "Starting virtual serial port loopback..."
          sudo socat -d -d pty,raw,echo=0,link=/dev/ttyS10 pty,raw,echo=0,link=/dev/ttyS11 &
          echo "Waiting for ports to initialize..."
          sleep 2
          echo "Running tests..."
          cd build && sudo ctest --output-on-failure

  clang:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y clang-18 g++ cmake libasio-dev socat qt6-base-dev qt6-serialport-dev

          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang-18 100
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-18 100

          clang --version
          clang++ --version

      - name: Configure CMake
        env:
          CC: /usr/bin/clang-18
          CXX: /usr/bin/clang++-18
        run: cmake -S . -B build -DPROTOCOMM_BUILD_TESTS=ON -DPROTOCOMM_BUILD_ASIO=ON -DPROTOCOMM_BUILD_QT=ON

      - name: Build
        run: cmake --build build

      - name: Run
        run: |
          echo "Starting virtual serial port loopback..."
          sudo socat -d -d pty,raw,echo=0,link=/dev/ttyS10 pty,raw,echo=0,link=/dev/ttyS11 &
          echo "Waiting for ports to initialize..."
          sleep 2
          echo "Running tests..."
          cd build && sudo ctest --output-on-failure
